[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_20"]

[phases.build]
cmds = ["composer install --no-dev", "npm install", "npm run build"]

[start]
cmd = "php -S 0.0.0.0:$PORT -t public"